version: '3'

services:
  universaltranslator:
    container_name: UniversalTranslator
    image: universaltranslator:1.0
    expose:
     - 80
    ports:
     - 8000:8000
    command: uvicorn main:app --reload --port 8000 --host 127.0.0.1
    network_mode: "host"
